--liquibase formatted sql

--changeset jsombie:1 splitStatements:true endDelimiter:\nGO
--comment: v1.0.1


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MSG]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[MSG](
	[NUM] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MSG] [varchar](max) NULL,
	[VER] [varchar](10) NULL,
	[TYP] [varchar](20) NULL,
	[TMS] [datetime] NULL,
	[USR] [varchar](50) NULL,
	[BDD] [varchar](50) NULL,
	[TAB] [varchar](50) NULL,
	[IDN] [varchar](50) NULL,
	[IDV] [varchar](50) NULL,
	[TAG] [varchar](50) NULL,
 CONSTRAINT [PK_MSG] PRIMARY KEY CLUSTERED
(
	[NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
/****** Object:  Index [IX_MSG_TMS]    Script Date: 09/07/2020 03:20:45 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MSG]') AND name = N'IX_MSG_TMS')
CREATE NONCLUSTERED INDEX [IX_MSG_TMS] ON [dbo].[MSG]
(
	[TMS] ASC
)
INCLUDE([USR]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_MSG1]    Script Date: 09/07/2020 03:20:45 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MSG]') AND name = N'IX_MSG1')
CREATE NONCLUSTERED INDEX [IX_MSG1] ON [dbo].[MSG]
(
	[TYP] ASC,
	[TAB] ASC,
	[IDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
